/**
 * Integration test Supabase clients.
 * Env vars sourced from .env.test.local (generated by supabase status -o env > .env.test.local)
 */
import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';

const envPath = path.resolve(process.cwd(), '.env.test.local');
const env = fs.existsSync(envPath)
  ? Object.fromEntries(
      fs.readFileSync(envPath, 'utf8')
        .split('\n')
        .filter((l) => l.includes('='))
        .map((l) => l.split('=').map((v) => v.trim()))
    )
  : {};

const API_URL = env.API_URL || process.env.API_URL || 'http://127.0.0.1:54321';
const ANON_KEY = env.ANON_KEY || process.env.ANON_KEY || '';
const SERVICE_KEY =
  env.SERVICE_ROLE_KEY || process.env.SERVICE_ROLE_KEY || '';

export const createAnonClient = () =>
  createClient(API_URL, ANON_KEY, {
    auth: { persistSession: false },
    global: { fetch: globalThis.fetch },
  });

export const createServiceClient = () =>
  createClient(API_URL, SERVICE_KEY, {
    auth: { persistSession: false },
    global: { fetch: globalThis.fetch },
  });
